language: lisp

env:
  matrix:
    - LISP=abcl
    - LISP=ccl
    - LISP=ccl32
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=cmucl
    - env: LISP=ecl

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - if [ "$LISP" = "allegro" ]; then sudo apt-get install libc6-dev-i386 libffi-dev:i386; fi
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl -l named-readtables
       -l fiveam
       -l trivial-escapes-test
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit 1)))'
       -e "(or (fiveam:run! 'trivial-escapes-test:|#\"-test-cases|)
               (uiop:quit 1))"
