# Come on, Travis. All I want is for `Common Lisp' to show up in my build dashboard.
language: common-lisp

env:
  matrix:
    - LISP=abcl
    - LISP=ccl
    - LISP=ccl32
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl COVERALLS=true
    - LISP=sbcl COVERALLS=true
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=cmucl
    - env: LISP=ecl
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always

install:
  - if [ "$LISP" = "allegro" ]; then sudo apt-get install libc6-dev-i386 libffi-dev:i386; fi
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  - if [ -n "$COVERALLS" ];
    then
      git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls;
      cd ~/lisp/cl-coveralls;
      git checkout a7dea1803f4b5aae8f939db6bbf26ab4389f71ff;
    fi

script:
  - if [ -n "$COVERALLS" ]
    ; then
      cl -l named-readtables
         -l fiveam
         -l cl-coveralls
         -l trivial-escapes-test
         -e '(in-package :cl-user)
             (setf *debugger-hook*
                   (lambda (c h)
                     (declare (ignore c h))
                     (uiop:quit 1)))'
         -e "(coveralls:with-coveralls (:exclude (list \"test\"))
               (asdf:test-system 'trivial-escapes))"
    ; else
      cl -l named-readtables
         -l fiveam
         -l trivial-escapes-test
         -e '(in-package :cl-user)
             (setf *debugger-hook*
                   (lambda (c h)
                     (declare (ignore c h))
                     (uiop:quit 1)))'
         -e "(or (fiveam:run! 'trivial-escapes-test:|#\"-test-cases|)
                 (uiop:quit 1))"
    ; fi